[loggers]
keys = root

[logger_root]
level = WARN
handlers = console
[handlers]
keys = console

[handler_console]
class = StreamHandler
args = (sys.stdout,)
level = NOTSET
formatter = default
[alembic]
script_location = migrations
sqlalchemy.url = postgresql://openclaw:openclaw@postgres:5432/openclaw

[formatters]
keys = default

[formatter_default]
format = %(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s
